#
# SPDX-FileCopyrightText: (C) 2017-2024 Red Hat, Inc.
#
# SPDX-License-Identifier: GPL-2.0-or-later
#

name: License check

on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: REUSE license check
        uses: fsfe/reuse-action@v4
